
server:
  port: 9092

spring:
  application:
    name: CANDIDATE-APP

eureka:
  client:
    register-with-eureka: true

  service-url: http://localhost:8761/

  spring:
    datasource:
      url: jdbc:h2:./candidateDB
      username: mk
      password:
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: create
      show-sql: true

    h2:
      console:
        enabled: true